Feat/add invitations to ardennes
betagouv/analyse-flux-insertion pull request #26
Opened 2021-04-14 15:53 UTC by qblanc

- Issue #17 
- En dépendance du merge de [cette PR](https://github.com/betagouv/rdv-solidarites.fr/pull/1344) de RDV-Solidarités

Dans le fichier Dates =>
- Ajout d'une méthode getFrenchDateString pour garder le format utilisé par les Ardennes

Dans le fichier Ardennes =>
- Ajout d'un useEffect, et d'un state "First check" ; ils permettent de lancer la nouvelle méthode checkUser après le chargement du fichier pour tous les utilisateurs qui ont un ID Rdv-Solidarités
- La méthode checkUser fait un get du User et vérifie où il en est dans son inscription (date d'invitation, date d'inscription)
- Ajout de la méthode generateInvitation, qui génère une nouvelle invitation et met à jour la date d'invitation
- La méthode checkUser est désormais appelée en cas de tentative de création d'un utilisateur existant déjà dans RDV-Solidarités

2021-04-15 12:03 UTC, aminedhobb reviewed
Good work @qblanc, je pense que la majeure partie des fonctionnalités sont en place 👏👏.
Je t'ai laissé quelques commentaires, beaucoup sont liées à des nommages de variables / méthodes et quelques unes des questions liées aux mécanismes.

Sinon j'ai deux remarques plus générales: 

- Ces fichiers commencent vraiment à être long je pense qu'il va peut-être falloir penser à extraire les fonctions qui appellent l'API de RDV-Solidarités dans un autre endroit.

- J'ai testé en local et ça me sort un résultat bizarre, mais peut-être que le fichier que j'upload n'a pas le bon format (ce sont les fichier XLS du dossier `Ardennes` que tu m'avais envoyé) : 
![image](https://user-images.githubusercontent.com/7602809/114865782-0d426180-9df3-11eb-995c-eed76d28669e.png)

2021-04-15 12:03 UTC, aminedhobb commented on lib/dates.js
> +function getFrenchDateString(date) {
Peut-être qu'on pourrait l'appeler `getFrenchFromatDateString` parce que french date ça fait un peu bizarre :D. T'en penses quoi ?

2021-04-15 12:03 UTC, aminedhobb commented on pages/experimentations/ardennes/index.js
> +  const usersUrl = `${RDV_SOLIDARITES_URL}/api/v1/users`;
👍

2021-04-15 12:03 UTC, aminedhobb commented on pages/experimentations/ardennes/index.js
> +  }, [usersData])
Si j'ai bien compris on rentre dans cette boucle que lors du chargement du fichier pour vérifier le statut des users que la première fois ?
Si c'est le cas `firstCheck` n'est pas un bon nom de variable parce que je lis la condition `firstCheck === false` comme "ce n'est pas le premier check". Je pense que `userStatusChecked` serait plus approprié comme nom.

Aussi est-ce que ce check est fait lorsqu'on reupload un fichier sans recharger la page ?

2021-04-15 12:03 UTC, aminedhobb commented on pages/experimentations/ardennes/index.js
> +    const getUserUrl = usersUrl + `/${userId}`;
peut-être que `userUrl` comme nom de variable serait plus analogue avec `usersUrl`

2021-04-15 12:03 UTC, aminedhobb commented on pages/experimentations/ardennes/index.js
> +            .split("-");
Je comprends ce que tu fais là mais ce serait peut-être cool de laisser un commentaire pour expliciter le format que l'on récupère pour `invitation_created_at`

2021-04-15 12:03 UTC, aminedhobb commented on pages/experimentations/ardennes/index.js
> +  const generateInvitation = (userId, userIndex) => {
Là aussi le nom de la méthode peut être confus parce qu'on ne génère pas vraiment l'invitation à cette étape. Que penses-tu de `retrieveInvitationUrl` ?

2021-04-15 12:03 UTC, aminedhobb commented on pages/experimentations/ardennes/index.js
> +  const checkUser = (userId, userIndex) => {
Le nom `checkUser` n'est pas explicite sur ce que cette méthode fait ici. 
Qu'est-ce que tu penses de `markUserInvitationStatus`?

2021-04-15 12:03 UTC, aminedhobb commented on pages/experimentations/ardennes/index.js
> +          generateInvitation(result.user.id, userIndex);
Donc ici tu récupères un URL d'invitation quelque soit le cas, que l'user ait un email ou pas ?

2021-04-15 12:10 UTC, qblanc commented
Merci Amine ! Je regarde tout ça.
Pour le fichier xls, c'est normal que tu ais des résultats bizarres, il faut y rajouter 4 colonnes pour que cela fonctionne : "ID RDV", "Date d'invitation", "Date d'inscription" et "Invitation".
Pour la longueur du fichier, je suis d'accord, c'est ce dont je parlais quand je te disais qu'il y aurait sans doute besoin de refacto, je vais essayer de découper ça en plusieurs fichiers.
N.B.: peut-être que tu peux enlever la capture d'écran, il y a les coordonnées de Charles dessus 🙂

2021-04-15 12:26 UTC, qblanc commented on pages/experimentations/ardennes/index.js
> +  }, [usersData])
oui le check est refait si un fichier est réuploadé. Mais dans ce cas toutes les données sont remises à zéro en fait, je "cumule" pas les fichiers. A priori Isabelle fonctionne avec un fichier unique, mais on peut adapter si nécessaire.

2021-04-15 13:00 UTC, qblanc commented on pages/experimentations/ardennes/index.js
> +  const generateInvitation = (userId, userIndex) => {
Si si, on la génère bel et bien. Et si on clique sur "regénérer", cela génère un nouveau token, une nouvelle invit, qui va remplacer l'autre

2021-04-15 13:02 UTC, qblanc commented on pages/experimentations/ardennes/index.js
> +  const checkUser = (userId, userIndex) => {
Je propose un compromis avec `checkUserInvitationStatus` 🙂

2021-04-15 13:02 UTC, qblanc commented on pages/experimentations/ardennes/index.js
> +          generateInvitation(result.user.id, userIndex);
Yes

2021-04-15 13:10 UTC, aminedhobb commented
> N.B.: peut-être que tu peux enlever la capture d'écran, il y a les coordonnées de Charles dessus 🙂

Ah yes j'avais zappé que c'était sa vrai adresse mail et téléphone 😅, bien vu @qblanc !
Pour le fichier je t'ai répondu sur Slack ;).

2021-04-16 17:45 UTC, aminedhobb commented on .env.development
> +NEXT_PUBLIC_RDV_SOLIDARITES_USER_PATH=/api/v1/users
Je suis pas sûr qu'il faille mettre le path en tant que variable d'environnement. Le définir comme tu le faisais me semblait suffisant.

2021-04-16 17:45 UTC, aminedhobb commented on components/createUserButton.js
> +export default function CreateUserButton({
La logique de ce component est trop liée à la page Ardennes, je pense pas qu'on veuille en faire un component à part entière parce qu'il ne pourra pas être réutilisé autre part.

2021-04-16 17:45 UTC, aminedhobb commented on lib/checkUserInvitationStatus.js
> +  }
Pareil ici, la logique est trop liée à la page Ardennes. Je pense qu'on peut essayer d'extraire la logique d'appeler l'endpoint de RDV-Solidarités seulement et garder cette logique d'updater le fichier excel dans la page Ardennes ?

2021-04-16 17:45 UTC, aminedhobb commented on lib/generateInvitation.js
> +  }
Là aussi je pense que cette partie doit rester sur la page Ardennes :)

2021-04-16 17:45 UTC, aminedhobb commented on lib/generateInvitation.js
> +const userUrl = RDV_SOLIDARITES_URL + process.env.NEXT_PUBLIC_RDV_SOLIDARITES_USER_PATH;
Je crois qu'il y a un problème d'indentation ici, est-ce que tu as `prettier`  d'installé sur ton IDE ?

2021-04-16 17:45 UTC, aminedhobb commented on lib/fetchUrl.js
> +export async function fetchUrl(url, token, method = "GET", body = null) {
Bon move d'extraire une méthode qui appelle les API externes 👍 .

Je suis pas convaincu par le nom `fetchUrl` parce que la méthode ne dépend pas de l'url uniquement. On peut mettre `appFetch` pour dire que c'est une abstraction de `fetch` de notre application mais on peut peut-être trouver mieux.

2021-04-16 17:45 UTC, aminedhobb commented on lib/fetchUrl.js
> +    .then((response) => response.json());
Je pense que si tu utilises `async / await` tu ne dois pas utiliser `.then`. 
Il faudrait faire 
```
const response = await fetch(...)
const result = await response.json()

2021-04-16 17:45 UTC, aminedhobb commented on lib/fetchUrl.js
> +  return result;
Ce serait bien de gérer les cas d'erreur mais on pourra le faire après.

2021-04-16 17:45 UTC, aminedhobb commented on pages/experimentations/ardennes/index.js
> +  const generateInvitation = (userId, userIndex) => {
Oui mais du coup ça génère un token et pas une invitation vu que l'endpoint sur RDV-Solidarités n'envoie pas le mail ?

2021-04-16 17:47 UTC, aminedhobb commented on pages/experimentations/ardennes/index.js
> +          generateInvitation(result.user.id, userIndex);
Tu fais ça dans l'optique de #18 ?

2021-04-16 17:49 UTC, aminedhobb commented on pages/experimentations/ardennes/index.js
> +  const checkUser = (userId, userIndex) => {
Oui ça peut marcher mais en fait le truc c'est que ça check puis ça update l'excel avec le résultat, donc ça fait 2 choses :).  L'idéal c'est que chaque fonction fasse une chose, et sinon de marquer tout ce que fait la fonction pour bien comprendre. On peut laisser `checkUserInvitationStatus` c'est pas très grave (ou remplacer par `checkAndMarkUserInviationStatus`) mais c'est juste pour donner l''idée.

2021-04-16 17:53 UTC, aminedhobb requested changes
Merci pour tes changements @qblanc ! 

Je t'ai laissé quelques commentaires. 
Pour les extractions, mon idée était d'extraire uniquement les appels API et pas la logique qui les entoure. On pourra créer un nouveau dossier `/actions` au projet pour ces appels. 

Si tu veux ou peut voir ça en pair programming, let me know !

2021-04-16 17:53 UTC, aminedhobb commented on lib/dates.js
> +function getFrenchFromatDateString(date) {
C'est complètement de ma faute mais j'ai fait une erreur de typo dans ma suggestion 😄 : c'est `Format` et pas `Fromat` qu'on voudrait mettre :).

2021-04-19 09:10 UTC, qblanc commented on components/createUserButton.js
> +export default function CreateUserButton({
C'est sûr que j'ai cherché ce que je pouvais extraire du fichier Ardennes pour le rendre moins long, comme tu m'avais demandé, mais j'ai aussi fait ce composant en pensant qu'il pouvait être réutilisé. Si on fait une expé avec un autre département qui ressemble beaucoup à celle d'Ardennes, la logique risque d'être très similaire ; la plus grosse différence a des chances de venir du fichier déposé par le département, le reste du process serait similiaire, et ce bouton et la logique qui va derrière pourrait être réutilisé. Qu'en penses-tu ?

2021-04-19 09:12 UTC, qblanc commented on lib/generateInvitation.js
> +const userUrl = RDV_SOLIDARITES_URL + process.env.NEXT_PUBLIC_RDV_SOLIDARITES_USER_PATH;
oui

2021-04-19 09:25 UTC, qblanc commented
Je ne peux pas répondre directement à ton commentaire sur generateInvitation, mais ça ne génère pas un token. Enfin, ça regénère un nouveau token, mais ça renvoie bien une url d'invitation, pas juste un token.

2021-04-19 11:58 UTC, aminedhobb approved these changes
Looks good to me @qblanc, merci pour les changements ⭐ !
Comme convenu on pensera à d'éventuelles refactos supplémentaires plus tard.

J'ai pas testé en local mais si c'est bon pour toi let's go 🚀.

2021-04-19 12:01 UTC, merged