Identifier nouveux demandeurs #19
betagouv/analyse-flux-insertion pull request #35
Opened 2021-04-21 14:44 UTC by aminedhobb

## Fonction principale

Dans cette PR j'introduis une nouvelle page qui sert à l'identification des nouveaux demandeurs RSA.
Pour l'instant, on ne sélectionne que les top entrants (voir #19) pour lesquels on affiche les informations de contacts (Nom, Prénom, Rôle, Numéro RSA et NIR).  

## Implémentation secondaire

En plus de cette fonctionnalité, j'introduis une refactorisation de la manière avec laquelle on interagit avec les fichiers XML. J'ai créé des readers (un pour les flux instructions et un pour les flux bénéficiaires qui héritent d'un base reader) qui sont des simples classes JS qui prennent en entrée le contenu des fichiers et dans laquelle on va englober toute la logique liée à l'extraction de de données de ces fichiers.
Ça servira à interagir plus facilement avec les fichiers depuis les différentes pages et de manière plus lisible (même si malheureusement le fait de devoir parcourir à chaque fois les flux bénéficiaires rend les choses un peu moins lisibles).

**Remarque**:
Les fichiers sont tous traitées à la volée et les informations non filtrées. On pourra penser à améliorer la visibilité en intégrant un système de pagination et en filtrant les doublons pour les fichiers volumineux.

2021-04-21 16:09 UTC, qblanc requested changes
Je n'ai pas testé en local pour le front, mais ça me paraît tout bon.
Pour le back, le principal souci vient des gros arrays de HTMLCollection qu'il faut éviter à mon avis (cf bug résolu hier)

2021-04-21 16:09 UTC, qblanc commented on components/fileHandler.js
> +        Glissez et déposez les fichiers {fileType && `"${fileType}"`} à analyser ou
Pourquoi les guillemets à l'intérieur des backticks ?

2021-04-21 16:09 UTC, qblanc commented on lib/readers/BaseFluxReader.js
> +    return new Array(...this.dom.getElementsByTagName("Personne"));
Je pense qu'il faudrait éviter de constituer ces arrays en tant que variable, vu que c'est ça qui fait bugger pour les gros fichiers.

2021-04-21 16:09 UTC, qblanc commented on lib/readers/FluxBeneficiaireReader.js
> +        newApplicants.push(applicant);
même remarque que la précédente ; en faisant ça, on reconstitue des énormes arrays de HTMLCollection.
Il faudrait essayer de limiter les grosses variables à ce qu'on ne peut pas éviter, c'est à dire ce qu'on veut en output. Peut-être en mettant la logique de newApplicantsPersonalData à l'intérieur de cette boucle for ?

2021-04-21 16:09 UTC, qblanc commented on lib/readers/FluxBeneficiaireReader.js
> +    return this.dom.getElementsByTagName("InfosFoyerRSA")[index];
pourquoi extraire ça ? Ce ne serait pas plus simple que la ligne 51 soit : 
`const application = this.dom.getElementsByTagName("InfosFoyerRSA")[i];` ?

2021-04-21 16:09 UTC, qblanc commented on lib/readers/FluxBeneficiaireReader.js
> +    return this.dom.getElementsByTagName("Personne")[index];
Pourquoi extraire cette partie plutôt que de l'écrire directement ligne 13 ?

2021-04-21 16:09 UTC, qblanc commented on lib/readers/FluxInstructionReader.js
> +    return new Array(...this.dom.getElementsByTagName("InfoDemandeRSA"));
Toujours la même remarque, c'est le genre d'array qui faisait bugger

2021-04-21 16:09 UTC, qblanc commented on pages/identification-beneficiaires/index.js
> +import { useCallback, useEffect, useState, useReducer } from "react";
useCallback et useEffect ne sont plus utilisés il me semble

2021-04-21 16:09 UTC, qblanc commented on pages/lecteur/cnaf/beneficiaire/index.js
> -      handleFile(devFile);
Est-ce que tu pourrais commenter ces useEffect plutôt que de les supprimer ? Comme ça je peux facilement les remettre en local chez moi, je trouve ça assez utile (malgré le bug qui fait un doublon sur le premier traitement, mais on pourrait facilement fix ça je pense)

2021-04-21 16:54 UTC, aminedhobb commented on components/fileHandler.js
> +        Glissez et déposez les fichiers {fileType && `"${fileType}"`} à analyser ou
J'avais mis des backtiks pour que "bénéficiaire" ou "instruction" soit entre guillemets, mais j'ai changé l'implémentation depuis: https://github.com/betagouv/analyse-flux-insertion/pull/35/commits/a8935a3944645bf2c271e27b2905c575857bdcf2

Maintenant je passe un message au `FileHandler` component pour passer des messages custom selon la page.

2021-04-21 16:57 UTC, aminedhobb commented on lib/readers/BaseFluxReader.js
> +    return new Array(...this.dom.getElementsByTagName("Personne"));
Je l'utilise encore pour les flux instructions pour lequel on a pas eu de bug reporté (je pense que les flux étant quotidien on est safe de ce côté là mais à vérifier).
Je pense du coup le garder pour les flux instructions, et si c'est amené à changer faudrait changer l'implémentation du traitement des flux instructions de la même manière que ce que tu avais fait pour les flux bénéficiaires.

2021-04-21 17:05 UTC, aminedhobb commented on lib/readers/FluxBeneficiaireReader.js
> +        newApplicants.push(applicant);
Ici on ne garde que les personnes qui sont des top entrants, la taille du tableau devrait normalement être bien moins importante que celle de tous les dossiers.
En plus j'ai besoin des informations de toutes ces personnes.
On pourra changer s'il le faut, je pense de toutes façons qu'à terme que le hack qu'on fait n'est pas viable et qu'il faudra trouver une solution plus pérenne 😕.

2021-04-21 17:05 UTC, aminedhobb commented on lib/readers/FluxBeneficiaireReader.js
> +    return this.dom.getElementsByTagName("InfosFoyerRSA")[index];
C'était pour séparer un peu les concerns et pouvoir réutiliser cette fonction si besoin. J'avoue qu'ici ça n'apporte pas un énorme plus mais je préfère quand même la garder si ça ne te dérange pas.

2021-04-21 17:06 UTC, aminedhobb commented on lib/readers/FluxBeneficiaireReader.js
> +    return this.dom.getElementsByTagName("Personne")[index];
Pareil c'était pour séparer un peu les concerns et pouvoir réutiliser cette fonction si besoin. J'avoue qu'ici aussi ça n'apporte pas un énorme plus mais je préfère quand même la garder si ça ne te dérange pas.

2021-04-21 17:06 UTC, aminedhobb commented on lib/readers/FluxInstructionReader.js
> +    return new Array(...this.dom.getElementsByTagName("InfoDemandeRSA"));
Pareil que plus haut j'utilise cette méthode que pour les flux instructions.

2021-04-21 17:06 UTC, aminedhobb commented on pages/identification-beneficiaires/index.js
> +import { useCallback, useEffect, useState, useReducer } from "react";
Oui bien vu 🕵️ ! Je les ai enlevé ici: https://github.com/betagouv/analyse-flux-insertion/pull/35/commits/af7a2083f85d2be3421054519baa294c92170ee8

2021-04-21 17:06 UTC, aminedhobb commented on pages/lecteur/cnaf/beneficiaire/index.js
> -      handleFile(devFile);
Ok ça marche je les ai remis ici en attendant de trouver une solution: https://github.com/betagouv/analyse-flux-insertion/pull/35/commits/af7a2083f85d2be3421054519baa294c92170ee8

Tu utilises ce hack dans quels cas déjà ?

2021-04-21 17:07 UTC, aminedhobb commented
> Je n'ai pas testé en local pour le front, mais ça me paraît tout bon.
> Pour le back, le principal souci vient des gros arrays de HTMLCollection qu'il faut éviter à mon avis (cf bug résolu hier)

Merci pour ta review @qblanc 🙌 ! 
J'ai répondu à certains de tes commentaires et appliqué quelques changements, dis-moi si tu as encore des suggestions !

2021-04-21 17:34 UTC, qblanc requested changes

2021-04-21 17:34 UTC, qblanc commented on lib/readers/FluxBeneficiaireReader.js
> +        newApplicants.push(applicant);
C'est surtout beaucoup moins gourmand en terme de récursivité (et donc de performance). A moins d'avoir un serveur pour stocker les fichiers ou les infos, on ne pourra pas faire beaucoup mieux je pense.
En mettant la logique de newApplicantsPersonalData dans cette boucle for, tu allèges déjà beaucoup ton array de newApplicants, tout en récupérant les infos quand même

2021-04-21 17:34 UTC, qblanc commented on lib/readers/BaseFluxReader.js
> +    return new Array(...this.dom.getElementsByTagName("Personne"));
Ok, mais le souci c'est que c'est le "BaseFluxReader", donc le reader du flux bénéficiaire l'utilise aussi, non ?

2021-04-21 17:38 UTC, qblanc commented on pages/lecteur/cnaf/beneficiaire/index.js
> -      handleFile(devFile);
Quand tu modifies ton code, tu n'as pas besoin de réuploader le fichier, il relance l'analyse en même temps que le refresh auto de la page. J'ai une idée pour corriger le bug du doublon, je vais essayer de voir si ça marche.

2021-04-21 17:39 UTC, qblanc commented
Pour BaseFluxReader, si la méthode n'est pas appellée dans FluxBeneficiaireReader, tu peux ignorer.

En revanche pour l'autre commentaire, je préfère vraiment ne pas prendre le risque de recréer le bug que l'on vient de supprimer, d'autant que le passage par la variable intermédiaire newApplicants ne me paraît pas apporter grand-chose (sinon pour des logiques d'organisation du code). Les fichiers mensuels sont vraiment énormes et je ne préfère pas parier sur le nombre de personnes en top entrants.

2021-04-21 19:58 UTC, aminedhobb commented on lib/readers/FluxBeneficiaireReader.js
> +        newApplicants.push(applicant);
Yes je pense pas qu'il y ait un problème de récursivité ici mais c'est juste qu'on instancie de grosses variables, c'est sûr que sans serveur c'est plus compliqué mais je vais voir si on peut pas améliorer ça.
Par contre dans tous les cas moi j'ai besoin d'avoir un tableau de la taille des nouveaux demandeurs pour pouvoir l'afficher dans la vu (ce qui est retourné par la méthode `newApplicantsPersonalData`).

2021-04-21 19:59 UTC, aminedhobb commented
> Pour BaseFluxReader, si la méthode n'est pas appellée dans FluxBeneficiaireReader, tu peux ignorer.

Non elle n'est pas appelée par le reader du flux bénéficiaire, mais je vais quand même la mettre au niveaux du reader du flux d'instruction pour éviter ce genre de confusion 👍 .

> En revanche pour l'autre commentaire, je préfère vraiment ne pas prendre le risque de recréer le bug que l'on vient de supprimer, d'autant que le passage par la variable intermédiaire newApplicants ne me paraît pas apporter grand-chose (sinon pour des logiques d'organisation du code). Les fichiers mensuels sont vraiment énormes et je ne préfère pas parier sur le nombre de personnes en top entrants.

Je t'ai répondu sur ce sujet [ici](https://github.com/betagouv/analyse-flux-insertion/pull/35#discussion_r617837537). Par contre juste pour être précis, cette fonctionnalité n'est utilisée que dans la nouvelle vue que j'ai crée (`/identification-beneficiaire`) et n'intervient pas sur les fonctionnalités précédentes.

2021-04-22 06:34 UTC, qblanc commented on lib/readers/FluxBeneficiaireReader.js
> +        newApplicants.push(applicant);
Yes tu as raison, ce n'est pas un problème récursivité. Ce que je voulais dire, c'est qu'à la fois ça fait constituer un énorme array, mais derrière, c'est aussi parce que tu constitues cet énorme array que tu te retrouves à utiliser un itérable dessus.
Si tu fais sauter la variable intermédiaire et que tu met directement la logique de newApplicantsPersonalData dedans, tu obtiens exactement le même résultat, tout en évitant un gros array en mémoire + une itération.

Pour le tableau de sortie, je suis d'accord qu'on a besoin d'en récupérer un assez large, mais autant ne stocker que ce dont on a besoin. Le tableau aura la même length mais si chaque élément du tableau c'est une petite string ou un petit tableau, ça ne pèse pas autant que si chaque élément du tableau c'est un gros noeud HTML je pense.
Vu qu'en plus quoi qu'il arrive on stocke déjà une variable énorme qu'est dom.

2021-04-22 06:37 UTC, qblanc commented
Je t'ai répondu [ici](https://github.com/betagouv/analyse-flux-insertion/pull/35#discussion_r618117042). À mon sens les corrections que je propose ne coûtent rien et peuvent nous éviter des bugs, mais je suis peut-être trop frileux. Je te laisse décider si tu veux les implémenter ou pas.

2021-04-22 06:37 UTC, qblanc submitted a review, later dismissed

2021-04-22 10:05 UTC, aminedhobb commented on lib/readers/FluxBeneficiaireReader.js
> +        newApplicants.push(applicant);
Ok, je sais pas si ça va améliorer grandement les performances mais vu que je l'utilise pas encre j'ai enlevé l'intermédiaire ici: https://github.com/betagouv/analyse-flux-insertion/pull/35/commits/3582261e961f9224cc766369e1e4076989a56d72

2021-04-22 10:26 UTC, qblanc approved these changes, later dismissed

2021-04-22 12:09 UTC, merged